/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CardShop: typeof import('./src/components/CardShop.vue')['default']
    Category: typeof import('./src/components/Category.vue')['default']
    Client: typeof import('./src/components/Client.vue')['default']
    DefaultLayout: typeof import('./src/components/DefaultLayout.vue')['default']
    Download: typeof import('./src/components/Download.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Map: typeof import('./src/components/Map.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    Pack: typeof import('./src/components/Pack.vue')['default']
    Partner: typeof import('./src/components/Partner.vue')['default']
    Popup: typeof import('./src/components/Popup.vue')['default']
    PopupDetails: typeof import('./src/components/PopupDetails.vue')['default']
    Product: typeof import('./src/components/Product.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
